#!/bin/bash
SOURCE=$(dirname -- "${BASH_SOURCE[0]}")

for i in 1 2 3 4 5 6 7 8 9 10; do cpupower frequency-info >> /dev/null; done && $SOURCE/../bin/histogram > $SOURCE/../data/histogram.out
python3 ../src/histogram/histogram.py
cat ../data/histogram.out