#!/bin/bash
SOURCE=$(dirname -- "${BASH_SOURCE[0]}")

echo "generating conflicting addresses"
$SOURCE/conflicting-addresses

echo -e "\nconfirming column bits"
$SOURCE/detect-col-bits

echo -e "\ntesting hypothesis"
$SOURCE/verify-dram-mapping